import shop1 from "@/assets/shop-1.jpg";
import shop2 from "@/assets/shop-2.jpg";
import shop3 from "@/assets/shop-3.jpg";
import refCut from "@/assets/ref-cut.jpg";
import type {
  Appointment,
  Barber,
  Customer,
  PointEntry,
  Review,
  Service,
  Shop,
  ShopNote,
} from "./types";

export const IMAGES = { shop1, shop2, shop3, refCut };

const d = (offset: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + offset);
  return dt.toISOString().slice(0, 10);
};

const fullWeek = (periods: { start: string; end: string }[][]) => periods;

const std = fullWeek([
  [], // Sun
  [
    { start: "09:00", end: "13:00" },
    { start: "14:00", end: "18:00" },
  ],
  [
    { start: "09:00", end: "13:00" },
    { start: "14:00", end: "18:00" },
  ],
  [
    { start: "09:00", end: "13:00" },
    { start: "14:00", end: "18:00" },
  ],
  [
    { start: "09:00", end: "13:00" },
    { start: "14:00", end: "19:00" },
  ],
  [
    { start: "09:00", end: "13:00" },
    { start: "14:00", end: "19:00" },
  ],
  [{ start: "10:00", end: "17:00" }], // Sat
]);

const late = fullWeek([
  [{ start: "11:00", end: "16:00" }],
  [{ start: "11:00", end: "20:00" }],
  [{ start: "11:00", end: "20:00" }],
  [],
  [{ start: "11:00", end: "20:00" }],
  [{ start: "11:00", end: "21:00" }],
  [{ start: "10:00", end: "18:00" }],
]);

export const shops: Shop[] = [
  {
    id: "shop-fade",
    name: "Fade & Co.",
    tagline: "Modern cuts, old-school care",
    description:
      "A neighbourhood barbershop focused on precision fades, classic scissor work and a proper hot-towel finish. Walk-ins welcome when the chairs are free.",
    photos: [shop1, shop3, shop2],
    rating: 4.8,
    reviewCount: 214,
    distanceKm: 0.6,
    area: "Indiranagar",
    address: "12, 100 Feet Road, Indiranagar",
    phone: "+91 98450 11223",
    hours: [
      { day: 0, open: null, close: null },
      { day: 1, open: "09:00", close: "18:00" },
      { day: 2, open: "09:00", close: "18:00" },
      { day: 3, open: "09:00", close: "18:00" },
      { day: 4, open: "09:00", close: "19:00" },
      { day: 5, open: "09:00", close: "19:00" },
      { day: 6, open: "10:00", close: "17:00" },
    ],
  },
  {
    id: "shop-tile",
    name: "The Tile Room",
    tagline: "One chair. Full attention.",
    description:
      "A single-chair studio for people who like taking their time. Appointment only, consultation included with every cut.",
    photos: [shop2, shop1],
    rating: 4.9,
    reviewCount: 87,
    distanceKm: 1.4,
    area: "Koramangala",
    address: "5th Block, 80 Feet Road, Koramangala",
    phone: "+91 98450 44556",
    hours: [
      { day: 0, open: "11:00", close: "16:00" },
      { day: 1, open: "11:00", close: "20:00" },
      { day: 2, open: "11:00", close: "20:00" },
      { day: 3, open: null, close: null },
      { day: 4, open: "11:00", close: "20:00" },
      { day: 5, open: "11:00", close: "21:00" },
      { day: 6, open: "10:00", close: "18:00" },
    ],
  },
  {
    id: "shop-neon",
    name: "Neon Barber Club",
    tagline: "Beards, blades and good music",
    description:
      "Vintage chairs, checkered floors and a beard menu that goes deeper than most. Great for a full groom before an event.",
    photos: [shop3, shop1],
    rating: 4.6,
    reviewCount: 341,
    distanceKm: 2.3,
    area: "HSR Layout",
    address: "27th Main, Sector 2, HSR Layout",
    phone: "+91 98450 77889",
    hours: [
      { day: 0, open: "10:00", close: "18:00" },
      { day: 1, open: "10:00", close: "20:00" },
      { day: 2, open: "10:00", close: "20:00" },
      { day: 3, open: "10:00", close: "20:00" },
      { day: 4, open: "10:00", close: "20:00" },
      { day: 5, open: "10:00", close: "21:00" },
      { day: 6, open: "09:00", close: "21:00" },
    ],
  },
  {
    id: "shop-corner",
    name: "Corner Cuts",
    tagline: "Quick, clean, close by",
    description: "Fast, honest haircuts for the neighbourhood. No frills, no waiting around.",
    photos: [shop1, shop2],
    rating: 4.3,
    reviewCount: 122,
    distanceKm: 3.1,
    area: "Domlur",
    address: "Old Airport Road, Domlur",
    phone: "+91 98450 99001",
    hours: [
      { day: 0, open: null, close: null },
      { day: 1, open: "09:00", close: "19:00" },
      { day: 2, open: "09:00", close: "19:00" },
      { day: 3, open: "09:00", close: "19:00" },
      { day: 4, open: "09:00", close: "19:00" },
      { day: 5, open: "09:00", close: "19:00" },
      { day: 6, open: "09:00", close: "19:00" },
    ],
  },
];

export const services: Service[] = [
  {
    id: "svc-haircut",
    shopId: "shop-fade",
    name: "Haircut",
    description: "Consultation, wash, cut and style.",
    price: 400,
    active: true,
  },
  {
    id: "svc-beard",
    shopId: "shop-fade",
    name: "Beard trim",
    description: "Shape-up, line work and beard oil finish.",
    price: 250,
    active: true,
  },
  {
    id: "svc-shave",
    shopId: "shop-fade",
    name: "Hot towel shave",
    description: "Straight razor shave with hot towel prep.",
    price: 350,
    active: true,
  },
  {
    id: "svc-combo",
    shopId: "shop-fade",
    name: "Haircut + beard",
    description: "The full reset. Cut, beard shape and finish.",
    price: 600,
    active: true,
  },
  {
    id: "svc-kids",
    shopId: "shop-fade",
    name: "Kids cut",
    description: "For under 12s. Patience included.",
    price: 250,
    active: false,
  },
  {
    id: "svc-t-haircut",
    shopId: "shop-tile",
    name: "Signature haircut",
    description: "Unhurried consultation and scissor cut.",
    price: 750,
    active: true,
  },
  {
    id: "svc-t-shave",
    shopId: "shop-tile",
    name: "Traditional shave",
    description: "Two-pass straight razor shave.",
    price: 550,
    active: true,
  },
  {
    id: "svc-n-haircut",
    shopId: "shop-neon",
    name: "Haircut",
    description: "Clipper or scissor cut, your call.",
    price: 350,
    active: true,
  },
  {
    id: "svc-n-beard",
    shopId: "shop-neon",
    name: "Beard sculpt",
    description: "Detailed beard shaping and conditioning.",
    price: 300,
    active: true,
  },
  {
    id: "svc-n-combo",
    shopId: "shop-neon",
    name: "Full groom",
    description: "Haircut, beard sculpt and hot towel.",
    price: 700,
    active: true,
  },
  {
    id: "svc-c-haircut",
    shopId: "shop-corner",
    name: "Haircut",
    description: "Straightforward cut, in and out.",
    price: 200,
    active: true,
  },
  {
    id: "svc-c-beard",
    shopId: "shop-corner",
    name: "Beard trim",
    description: "Quick clean-up.",
    price: 120,
    active: true,
  },
];

export const barbers: Barber[] = [
  {
    id: "brb-raj",
    shopId: "shop-fade",
    name: "Raj Menon",
    bio: "Twelve years behind the chair. Fast, precise skin fades.",
    active: true,
    rating: 4.9,
    reviewCount: 138,
    points: 420,
    services: [
      { serviceId: "svc-haircut", durationMin: 15, active: true },
      { serviceId: "svc-beard", durationMin: 15, active: true },
      { serviceId: "svc-combo", durationMin: 30, active: true },
    ],
    schedule: std,
    timeOff: [],
  },
  {
    id: "brb-arun",
    shopId: "shop-fade",
    name: "Arun Pillai",
    bio: "Scissor-work specialist. Takes his time, and it shows.",
    active: true,
    rating: 4.8,
    reviewCount: 96,
    points: 260,
    services: [
      { serviceId: "svc-haircut", durationMin: 25, active: true },
      { serviceId: "svc-shave", durationMin: 30, priceOverride: 400, active: true },
      { serviceId: "svc-combo", durationMin: 50, active: true },
    ],
    schedule: std,
    timeOff: [{ id: "to-1", date: d(3), reason: "Family leave" }],
  },
  {
    id: "brb-sam",
    shopId: "shop-fade",
    name: "Sameer Khan",
    bio: "Beard guy. Straight razor certified.",
    active: true,
    rating: 4.7,
    reviewCount: 64,
    points: 95,
    services: [
      { serviceId: "svc-beard", durationMin: 20, active: true },
      { serviceId: "svc-shave", durationMin: 25, active: true },
      { serviceId: "svc-haircut", durationMin: 30, active: false },
    ],
    schedule: late,
    timeOff: [],
  },
  {
    id: "brb-tile-nik",
    shopId: "shop-tile",
    name: "Nikhil Rao",
    bio: "Owner-operator. One chair, one client at a time.",
    active: true,
    rating: 4.9,
    reviewCount: 87,
    points: 510,
    services: [
      { serviceId: "svc-t-haircut", durationMin: 45, active: true },
      { serviceId: "svc-t-shave", durationMin: 40, active: true },
    ],
    schedule: late,
    timeOff: [],
  },
  {
    id: "brb-neon-dev",
    shopId: "shop-neon",
    name: "Dev Sharma",
    bio: "Fades, tapers and the loudest playlist in the shop.",
    active: true,
    rating: 4.6,
    reviewCount: 151,
    points: 180,
    services: [
      { serviceId: "svc-n-haircut", durationMin: 20, active: true },
      { serviceId: "svc-n-combo", durationMin: 45, active: true },
    ],
    schedule: std,
    timeOff: [],
  },
  {
    id: "brb-neon-ali",
    shopId: "shop-neon",
    name: "Ali Hussain",
    bio: "Beard sculpting and classic shaves.",
    active: true,
    rating: 4.7,
    reviewCount: 88,
    points: 140,
    services: [
      { serviceId: "svc-n-beard", durationMin: 25, active: true },
      { serviceId: "svc-n-haircut", durationMin: 30, priceOverride: 400, active: true },
    ],
    schedule: late,
    timeOff: [],
  },
  {
    id: "brb-corner-vin",
    shopId: "shop-corner",
    name: "Vinod Kumar",
    bio: "Neighbourhood barber since 2009.",
    active: true,
    rating: 4.3,
    reviewCount: 122,
    points: 60,
    services: [
      { serviceId: "svc-c-haircut", durationMin: 20, active: true },
      { serviceId: "svc-c-beard", durationMin: 10, active: true },
    ],
    schedule: std,
    timeOff: [],
  },
];

export const customers: Customer[] = [
  {
    id: "cus-you",
    name: "John Fernandes",
    phone: "+91 98800 12345",
    email: "john@example.com",
    preferences: "Number 2 on the sides, scissors on top. Not a fan of gel.",
    savedPhotos: [{ id: "sp-1", url: refCut, caption: "My go-to textured crop" }],
  },
  {
    id: "cus-mira",
    name: "Mira Shetty",
    phone: "+91 98800 55512",
    email: "mira@example.com",
    preferences: "Short back, keep the length on top.",
    savedPhotos: [],
  },
  {
    id: "cus-tanvir",
    name: "Tanvir Ahmed",
    phone: "+91 98800 99887",
    email: "tanvir@example.com",
    preferences: "Beard square at the jaw.",
    savedPhotos: [],
  },
  {
    id: "cus-priya",
    name: "Priya Nair",
    phone: "+91 98800 33221",
    email: "priya@example.com",
    preferences: "",
    savedPhotos: [],
  },
];

export const seedAppointments: Appointment[] = [
  {
    id: "apt-1",
    shopId: "shop-fade",
    barberId: "brb-raj",
    serviceId: "svc-haircut",
    customerId: "cus-you",
    date: d(2),
    time: "10:30",
    durationMin: 15,
    price: 400,
    status: "booked",
    note: "Coming straight from work, might be 5 min late.",
    referencePhotos: [{ id: "rp-1", url: refCut, caption: "Reference for this appointment" }],
    createdAt: d(-1),
  },
  {
    id: "apt-2",
    shopId: "shop-neon",
    barberId: "brb-neon-dev",
    serviceId: "svc-n-combo",
    customerId: "cus-you",
    date: d(-21),
    time: "17:00",
    durationMin: 45,
    price: 700,
    status: "completed",
    referencePhotos: [],
    completion: {
      actualService: "Full groom + eyebrow tidy",
      finalPrice: 750,
      notes: "Prefers a mid fade, not high. Sensitive skin on the neck.",
      finishedPhoto: refCut,
      pointsAwarded: 10,
    },
    createdAt: d(-28),
  },
  {
    id: "apt-3",
    shopId: "shop-fade",
    barberId: "brb-arun",
    serviceId: "svc-combo",
    customerId: "cus-you",
    date: d(-48),
    time: "11:00",
    durationMin: 50,
    price: 600,
    status: "completed",
    referencePhotos: [],
    completion: {
      actualService: "Haircut + beard",
      finalPrice: 600,
      notes: "Scissor cut on top, tight beard line.",
      pointsAwarded: 10,
    },
    createdAt: d(-55),
  },
  {
    id: "apt-4",
    shopId: "shop-fade",
    barberId: "brb-raj",
    serviceId: "svc-haircut",
    customerId: "cus-mira",
    date: d(0),
    time: "10:30",
    durationMin: 15,
    price: 400,
    status: "booked",
    referencePhotos: [],
    createdAt: d(-3),
  },
  {
    id: "apt-5",
    shopId: "shop-fade",
    barberId: "brb-arun",
    serviceId: "svc-haircut",
    customerId: "cus-tanvir",
    date: d(0),
    time: "12:00",
    durationMin: 25,
    price: 400,
    status: "booked",
    note: "Wedding on Saturday.",
    referencePhotos: [{ id: "rp-2", url: refCut, caption: "Reference for this appointment" }],
    createdAt: d(-2),
  },
  {
    id: "apt-6",
    shopId: "shop-fade",
    barberId: "brb-sam",
    serviceId: "svc-beard",
    customerId: "cus-priya",
    date: d(0),
    time: "15:00",
    durationMin: 20,
    price: 250,
    status: "booked",
    referencePhotos: [],
    createdAt: d(-1),
  },
  {
    id: "apt-7",
    shopId: "shop-fade",
    barberId: "brb-raj",
    serviceId: "svc-combo",
    customerId: "cus-tanvir",
    date: d(-14),
    time: "16:00",
    durationMin: 30,
    price: 600,
    status: "completed",
    referencePhotos: [],
    completion: {
      actualService: "Haircut + beard",
      finalPrice: 650,
      notes: "Added a hot towel. Books roughly every 3 weeks.",
      pointsAwarded: 10,
    },
    createdAt: d(-20),
  },
  {
    id: "apt-8",
    shopId: "shop-fade",
    barberId: "brb-raj",
    serviceId: "svc-haircut",
    customerId: "cus-priya",
    date: d(-7),
    time: "09:30",
    durationMin: 15,
    price: 400,
    status: "no_show",
    referencePhotos: [],
    createdAt: d(-10),
  },
  {
    id: "apt-9",
    shopId: "shop-fade",
    barberId: "brb-arun",
    serviceId: "svc-haircut",
    customerId: "cus-mira",
    date: d(-30),
    time: "14:00",
    durationMin: 25,
    price: 400,
    status: "completed",
    referencePhotos: [],
    completion: {
      actualService: "Haircut",
      finalPrice: 400,
      pointsAwarded: 10,
      notes: "Likes it dry-cut, no wash.",
    },
    createdAt: d(-34),
  },
  {
    id: "apt-10",
    shopId: "shop-fade",
    barberId: "brb-raj",
    serviceId: "svc-beard",
    customerId: "cus-mira",
    date: d(-60),
    time: "18:00",
    durationMin: 15,
    price: 250,
    status: "cancelled",
    referencePhotos: [],
    createdAt: d(-62),
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    shopId: "shop-fade",
    barberId: "brb-raj",
    appointmentId: "apt-7",
    customerId: "cus-tanvir",
    customerName: "Tanvir A.",
    shopRating: 5,
    barberRating: 5,
    text: "Raj got me in and out in twenty minutes and the fade was perfect. Best shop in the area.",
    date: d(-13),
  },
  {
    id: "rev-2",
    shopId: "shop-fade",
    barberId: "brb-arun",
    appointmentId: "apt-9",
    customerId: "cus-mira",
    customerName: "Mira S.",
    shopRating: 5,
    barberRating: 5,
    text: "Arun actually listens. He took his time and the shape has grown out really well.",
    date: d(-29),
  },
  {
    id: "rev-3",
    shopId: "shop-fade",
    appointmentId: "apt-3",
    customerId: "cus-you",
    customerName: "John F.",
    shopRating: 4,
    text: "Great cut, slightly long wait even with an appointment.",
    date: d(-47),
  },
  {
    id: "rev-4",
    shopId: "shop-neon",
    barberId: "brb-neon-dev",
    appointmentId: "apt-2",
    customerId: "cus-you",
    customerName: "John F.",
    shopRating: 5,
    barberRating: 5,
    text: "Full groom before a wedding. Worth every rupee.",
    date: d(-20),
  },
];

export const shopNotes: ShopNote[] = [
  {
    id: "note-1",
    shopId: "shop-fade",
    customerId: "cus-you",
    text: "Prefers Raj. Number 2 fade, scissors on top. Books around every 4 weeks.",
    date: d(-48),
    author: "Arun Pillai",
  },
  {
    id: "note-2",
    shopId: "shop-fade",
    customerId: "cus-tanvir",
    text: "Sensitive skin — use the unscented balm.",
    date: d(-14),
    author: "Raj Menon",
  },
];

export const pointEntries: PointEntry[] = [
  { id: "pt-1", barberId: "brb-raj", points: 10, reason: "Completed record — Tanvir A.", date: d(-14) },
  { id: "pt-2", barberId: "brb-raj", points: 10, reason: "Completed record — Mira S.", date: d(-21) },
  { id: "pt-3", barberId: "brb-arun", points: 10, reason: "Completed record — John F.", date: d(-48) },
  { id: "pt-4", barberId: "brb-arun", points: 10, reason: "Completed record — Mira S.", date: d(-30) },
];
