/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsAppointmentIdRouteImport } from './routes/bookings.$appointmentId'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageShopIdRouteImport } from './routes/manage.$shopId'
import { Route as ManageShopIdIndexRouteImport } from './routes/manage.$shopId.index'
import { Route as ManageShopIdPointsRouteImport } from './routes/manage.$shopId.points'
import { Route as ManageShopIdReviewsRouteImport } from './routes/manage.$shopId.reviews'
import { Route as ManageShopIdScheduleRouteImport } from './routes/manage.$shopId.schedule'
import { Route as ManageShopIdServicesRouteImport } from './routes/manage.$shopId.services'
import { Route as ManageShopIdSettingsRouteImport } from './routes/manage.$shopId.settings'
import { Route as ShopsShopIdIndexRouteImport } from './routes/shops.$shopId.index'
import { Route as ShopsShopIdBookRouteImport } from './routes/shops.$shopId.book'
import { Route as ManageShopIdAppointmentsIndexRouteImport } from './routes/manage.$shopId.appointments.index'
import { Route as ManageShopIdAppointmentsAppointmentIdRouteImport } from './routes/manage.$shopId.appointments.$appointmentId'
import { Route as ManageShopIdBarbersIndexRouteImport } from './routes/manage.$shopId.barbers.index'
import { Route as ManageShopIdBarbersBarberIdRouteImport } from './routes/manage.$shopId.barbers.$barberId'
import { Route as ManageShopIdCustomersIndexRouteImport } from './routes/manage.$shopId.customers.index'
import { Route as ManageShopIdCustomersCustomerIdRouteImport } from './routes/manage.$shopId.customers.$customerId'
import { Route as ShopsShopIdBarbersBarberIdRouteImport } from './routes/shops.$shopId.barbers.$barberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsAppointmentIdRoute = BookingsAppointmentIdRouteImport.update({
  id: '/bookings/$appointmentId',
  path: '/bookings/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageShopIdRoute = ManageShopIdRouteImport.update({
  id: '/manage/$shopId',
  path: '/manage/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageShopIdIndexRoute = ManageShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ManageShopIdPointsRoute = ManageShopIdPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ManageShopIdReviewsRoute = ManageShopIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ManageShopIdScheduleRoute = ManageShopIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ManageShopIdServicesRoute = ManageShopIdServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ManageShopIdSettingsRoute = ManageShopIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageShopIdRoute,
} as any)
const ShopsShopIdIndexRoute = ShopsShopIdIndexRouteImport.update({
  id: '/shops/$shopId/',
  path: '/shops/$shopId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdBookRoute = ShopsShopIdBookRouteImport.update({
  id: '/shops/$shopId/book',
  path: '/shops/$shopId/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageShopIdAppointmentsIndexRoute =
  ManageShopIdAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ManageShopIdAppointmentsAppointmentIdRoute =
  ManageShopIdAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ManageShopIdBarbersIndexRoute =
  ManageShopIdBarbersIndexRouteImport.update({
    id: '/barbers/',
    path: '/barbers/',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ManageShopIdBarbersBarberIdRoute =
  ManageShopIdBarbersBarberIdRouteImport.update({
    id: '/barbers/$barberId',
    path: '/barbers/$barberId',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ManageShopIdCustomersIndexRoute =
  ManageShopIdCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ManageShopIdCustomersCustomerIdRoute =
  ManageShopIdCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => ManageShopIdRoute,
  } as any)
const ShopsShopIdBarbersBarberIdRoute =
  ShopsShopIdBarbersBarberIdRouteImport.update({
    id: '/shops/$shopId/barbers/$barberId',
    path: '/shops/$shopId/barbers/$barberId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/bookings/$appointmentId': typeof BookingsAppointmentIdRoute
  '/manage/$shopId': typeof ManageShopIdRouteWithChildren
  '/bookings/': typeof BookingsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/$shopId/points': typeof ManageShopIdPointsRoute
  '/manage/$shopId/reviews': typeof ManageShopIdReviewsRoute
  '/manage/$shopId/schedule': typeof ManageShopIdScheduleRoute
  '/manage/$shopId/services': typeof ManageShopIdServicesRoute
  '/manage/$shopId/settings': typeof ManageShopIdSettingsRoute
  '/shops/$shopId/book': typeof ShopsShopIdBookRoute
  '/manage/$shopId/': typeof ManageShopIdIndexRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/manage/$shopId/appointments/$appointmentId': typeof ManageShopIdAppointmentsAppointmentIdRoute
  '/manage/$shopId/barbers/$barberId': typeof ManageShopIdBarbersBarberIdRoute
  '/manage/$shopId/customers/$customerId': typeof ManageShopIdCustomersCustomerIdRoute
  '/shops/$shopId/barbers/$barberId': typeof ShopsShopIdBarbersBarberIdRoute
  '/manage/$shopId/appointments/': typeof ManageShopIdAppointmentsIndexRoute
  '/manage/$shopId/barbers/': typeof ManageShopIdBarbersIndexRoute
  '/manage/$shopId/customers/': typeof ManageShopIdCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/bookings/$appointmentId': typeof BookingsAppointmentIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/manage': typeof ManageIndexRoute
  '/manage/$shopId/points': typeof ManageShopIdPointsRoute
  '/manage/$shopId/reviews': typeof ManageShopIdReviewsRoute
  '/manage/$shopId/schedule': typeof ManageShopIdScheduleRoute
  '/manage/$shopId/services': typeof ManageShopIdServicesRoute
  '/manage/$shopId/settings': typeof ManageShopIdSettingsRoute
  '/shops/$shopId/book': typeof ShopsShopIdBookRoute
  '/manage/$shopId': typeof ManageShopIdIndexRoute
  '/shops/$shopId': typeof ShopsShopIdIndexRoute
  '/manage/$shopId/appointments/$appointmentId': typeof ManageShopIdAppointmentsAppointmentIdRoute
  '/manage/$shopId/barbers/$barberId': typeof ManageShopIdBarbersBarberIdRoute
  '/manage/$shopId/customers/$customerId': typeof ManageShopIdCustomersCustomerIdRoute
  '/shops/$shopId/barbers/$barberId': typeof ShopsShopIdBarbersBarberIdRoute
  '/manage/$shopId/appointments': typeof ManageShopIdAppointmentsIndexRoute
  '/manage/$shopId/barbers': typeof ManageShopIdBarbersIndexRoute
  '/manage/$shopId/customers': typeof ManageShopIdCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/bookings/$appointmentId': typeof BookingsAppointmentIdRoute
  '/manage/$shopId': typeof ManageShopIdRouteWithChildren
  '/bookings/': typeof BookingsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/$shopId/points': typeof ManageShopIdPointsRoute
  '/manage/$shopId/reviews': typeof ManageShopIdReviewsRoute
  '/manage/$shopId/schedule': typeof ManageShopIdScheduleRoute
  '/manage/$shopId/services': typeof ManageShopIdServicesRoute
  '/manage/$shopId/settings': typeof ManageShopIdSettingsRoute
  '/shops/$shopId/book': typeof ShopsShopIdBookRoute
  '/manage/$shopId/': typeof ManageShopIdIndexRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/manage/$shopId/appointments/$appointmentId': typeof ManageShopIdAppointmentsAppointmentIdRoute
  '/manage/$shopId/barbers/$barberId': typeof ManageShopIdBarbersBarberIdRoute
  '/manage/$shopId/customers/$customerId': typeof ManageShopIdCustomersCustomerIdRoute
  '/shops/$shopId/barbers/$barberId': typeof ShopsShopIdBarbersBarberIdRoute
  '/manage/$shopId/appointments/': typeof ManageShopIdAppointmentsIndexRoute
  '/manage/$shopId/barbers/': typeof ManageShopIdBarbersIndexRoute
  '/manage/$shopId/customers/': typeof ManageShopIdCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/bookings/$appointmentId'
    | '/manage/$shopId'
    | '/bookings/'
    | '/manage/'
    | '/manage/$shopId/points'
    | '/manage/$shopId/reviews'
    | '/manage/$shopId/schedule'
    | '/manage/$shopId/services'
    | '/manage/$shopId/settings'
    | '/shops/$shopId/book'
    | '/manage/$shopId/'
    | '/shops/$shopId/'
    | '/manage/$shopId/appointments/$appointmentId'
    | '/manage/$shopId/barbers/$barberId'
    | '/manage/$shopId/customers/$customerId'
    | '/shops/$shopId/barbers/$barberId'
    | '/manage/$shopId/appointments/'
    | '/manage/$shopId/barbers/'
    | '/manage/$shopId/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/bookings/$appointmentId'
    | '/bookings'
    | '/manage'
    | '/manage/$shopId/points'
    | '/manage/$shopId/reviews'
    | '/manage/$shopId/schedule'
    | '/manage/$shopId/services'
    | '/manage/$shopId/settings'
    | '/shops/$shopId/book'
    | '/manage/$shopId'
    | '/shops/$shopId'
    | '/manage/$shopId/appointments/$appointmentId'
    | '/manage/$shopId/barbers/$barberId'
    | '/manage/$shopId/customers/$customerId'
    | '/shops/$shopId/barbers/$barberId'
    | '/manage/$shopId/appointments'
    | '/manage/$shopId/barbers'
    | '/manage/$shopId/customers'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/bookings/$appointmentId'
    | '/manage/$shopId'
    | '/bookings/'
    | '/manage/'
    | '/manage/$shopId/points'
    | '/manage/$shopId/reviews'
    | '/manage/$shopId/schedule'
    | '/manage/$shopId/services'
    | '/manage/$shopId/settings'
    | '/shops/$shopId/book'
    | '/manage/$shopId/'
    | '/shops/$shopId/'
    | '/manage/$shopId/appointments/$appointmentId'
    | '/manage/$shopId/barbers/$barberId'
    | '/manage/$shopId/customers/$customerId'
    | '/shops/$shopId/barbers/$barberId'
    | '/manage/$shopId/appointments/'
    | '/manage/$shopId/barbers/'
    | '/manage/$shopId/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ProfileRoute: typeof ProfileRoute
  BookingsAppointmentIdRoute: typeof BookingsAppointmentIdRoute
  ManageShopIdRoute: typeof ManageShopIdRouteWithChildren
  BookingsIndexRoute: typeof BookingsIndexRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ShopsShopIdBookRoute: typeof ShopsShopIdBookRoute
  ShopsShopIdIndexRoute: typeof ShopsShopIdIndexRoute
  ShopsShopIdBarbersBarberIdRoute: typeof ShopsShopIdBarbersBarberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$appointmentId': {
      id: '/bookings/$appointmentId'
      path: '/bookings/$appointmentId'
      fullPath: '/bookings/$appointmentId'
      preLoaderRoute: typeof BookingsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$shopId': {
      id: '/manage/$shopId'
      path: '/manage/$shopId'
      fullPath: '/manage/$shopId'
      preLoaderRoute: typeof ManageShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$shopId/': {
      id: '/manage/$shopId/'
      path: '/'
      fullPath: '/manage/$shopId/'
      preLoaderRoute: typeof ManageShopIdIndexRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/points': {
      id: '/manage/$shopId/points'
      path: '/points'
      fullPath: '/manage/$shopId/points'
      preLoaderRoute: typeof ManageShopIdPointsRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/reviews': {
      id: '/manage/$shopId/reviews'
      path: '/reviews'
      fullPath: '/manage/$shopId/reviews'
      preLoaderRoute: typeof ManageShopIdReviewsRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/schedule': {
      id: '/manage/$shopId/schedule'
      path: '/schedule'
      fullPath: '/manage/$shopId/schedule'
      preLoaderRoute: typeof ManageShopIdScheduleRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/services': {
      id: '/manage/$shopId/services'
      path: '/services'
      fullPath: '/manage/$shopId/services'
      preLoaderRoute: typeof ManageShopIdServicesRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/settings': {
      id: '/manage/$shopId/settings'
      path: '/settings'
      fullPath: '/manage/$shopId/settings'
      preLoaderRoute: typeof ManageShopIdSettingsRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/shops/$shopId/': {
      id: '/shops/$shopId/'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof ShopsShopIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/book': {
      id: '/shops/$shopId/book'
      path: '/shops/$shopId/book'
      fullPath: '/shops/$shopId/book'
      preLoaderRoute: typeof ShopsShopIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$shopId/appointments/': {
      id: '/manage/$shopId/appointments/'
      path: '/appointments'
      fullPath: '/manage/$shopId/appointments/'
      preLoaderRoute: typeof ManageShopIdAppointmentsIndexRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/appointments/$appointmentId': {
      id: '/manage/$shopId/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/manage/$shopId/appointments/$appointmentId'
      preLoaderRoute: typeof ManageShopIdAppointmentsAppointmentIdRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/barbers/': {
      id: '/manage/$shopId/barbers/'
      path: '/barbers'
      fullPath: '/manage/$shopId/barbers/'
      preLoaderRoute: typeof ManageShopIdBarbersIndexRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/barbers/$barberId': {
      id: '/manage/$shopId/barbers/$barberId'
      path: '/barbers/$barberId'
      fullPath: '/manage/$shopId/barbers/$barberId'
      preLoaderRoute: typeof ManageShopIdBarbersBarberIdRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/customers/': {
      id: '/manage/$shopId/customers/'
      path: '/customers'
      fullPath: '/manage/$shopId/customers/'
      preLoaderRoute: typeof ManageShopIdCustomersIndexRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/manage/$shopId/customers/$customerId': {
      id: '/manage/$shopId/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/manage/$shopId/customers/$customerId'
      preLoaderRoute: typeof ManageShopIdCustomersCustomerIdRouteImport
      parentRoute: typeof ManageShopIdRoute
    }
    '/shops/$shopId/barbers/$barberId': {
      id: '/shops/$shopId/barbers/$barberId'
      path: '/shops/$shopId/barbers/$barberId'
      fullPath: '/shops/$shopId/barbers/$barberId'
      preLoaderRoute: typeof ShopsShopIdBarbersBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManageShopIdRouteChildren {
  ManageShopIdPointsRoute: typeof ManageShopIdPointsRoute
  ManageShopIdReviewsRoute: typeof ManageShopIdReviewsRoute
  ManageShopIdScheduleRoute: typeof ManageShopIdScheduleRoute
  ManageShopIdServicesRoute: typeof ManageShopIdServicesRoute
  ManageShopIdSettingsRoute: typeof ManageShopIdSettingsRoute
  ManageShopIdIndexRoute: typeof ManageShopIdIndexRoute
  ManageShopIdAppointmentsAppointmentIdRoute: typeof ManageShopIdAppointmentsAppointmentIdRoute
  ManageShopIdBarbersBarberIdRoute: typeof ManageShopIdBarbersBarberIdRoute
  ManageShopIdCustomersCustomerIdRoute: typeof ManageShopIdCustomersCustomerIdRoute
  ManageShopIdAppointmentsIndexRoute: typeof ManageShopIdAppointmentsIndexRoute
  ManageShopIdBarbersIndexRoute: typeof ManageShopIdBarbersIndexRoute
  ManageShopIdCustomersIndexRoute: typeof ManageShopIdCustomersIndexRoute
}

const ManageShopIdRouteChildren: ManageShopIdRouteChildren = {
  ManageShopIdPointsRoute: ManageShopIdPointsRoute,
  ManageShopIdReviewsRoute: ManageShopIdReviewsRoute,
  ManageShopIdScheduleRoute: ManageShopIdScheduleRoute,
  ManageShopIdServicesRoute: ManageShopIdServicesRoute,
  ManageShopIdSettingsRoute: ManageShopIdSettingsRoute,
  ManageShopIdIndexRoute: ManageShopIdIndexRoute,
  ManageShopIdAppointmentsAppointmentIdRoute:
    ManageShopIdAppointmentsAppointmentIdRoute,
  ManageShopIdBarbersBarberIdRoute: ManageShopIdBarbersBarberIdRoute,
  ManageShopIdCustomersCustomerIdRoute: ManageShopIdCustomersCustomerIdRoute,
  ManageShopIdAppointmentsIndexRoute: ManageShopIdAppointmentsIndexRoute,
  ManageShopIdBarbersIndexRoute: ManageShopIdBarbersIndexRoute,
  ManageShopIdCustomersIndexRoute: ManageShopIdCustomersIndexRoute,
}

const ManageShopIdRouteWithChildren = ManageShopIdRoute._addFileChildren(
  ManageShopIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ProfileRoute: ProfileRoute,
  BookingsAppointmentIdRoute: BookingsAppointmentIdRoute,
  ManageShopIdRoute: ManageShopIdRouteWithChildren,
  BookingsIndexRoute: BookingsIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  ShopsShopIdBookRoute: ShopsShopIdBookRoute,
  ShopsShopIdIndexRoute: ShopsShopIdIndexRoute,
  ShopsShopIdBarbersBarberIdRoute: ShopsShopIdBarbersBarberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
